language: android
jdk:
    - oraclejdk8
android:
    components:
        - extra-google-m2repository
        - extra-android-m2repository
        - build-tools-25.0.1

        - android-25

        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-25
